SELECT NAME, COUNT(*) AS NUM_OF_ORDERS
FROM MEAL
GROUP BY NAME;

SELECT SUM(PRICE) AS TOTAL_REVENUE
FROM MEAL
WHERE PRICE > 15;

SELECT COUNT(*) AS NUM_OF_MEALS
FROM MEAL
WHERE CALORIES > 500;

SELECT SUM(PRICE) AS TOTAL_PRICE
FROM MEAL
WHERE LOWER(NAME) LIKE '%s%';

SELECT NAME, COUNT(*) AS NUM_OF_ORDERS
FROM MEAL
WHERE DATE_ORDERED < '2023-05-15 01:14:00'
GROUP BY NAME;