CREATE TABLE MEAL (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT
);
INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
('Grilled Chicken Sandwich', 8.99, 400),
('Pesto Pasta', 10.99, 550),
('Steak and Mash', 19.99, 800),
('Sushi Platter', 15.99, 700);

CREATE TABLE MEAL_ORDER (
TIME_MEAL_ORDERED TIMESTAMP DEFAULT NOW(),
MEAL_NAME VARCHAR(255));

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (NOW(), 'Spaghetti Bolognese');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 1 HOUR), 'Grilled Chicken Sandwich');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 2 HOUR), 'Pesto Pasta');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 3 HOUR), 'Pesto Pasta');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 4 HOUR), 'Grilled Chicken Sandwich');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 5 HOUR), 'Pesto Pasta');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 6 HOUR), 'Spaghetti Bolognese');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 7 HOUR), 'Pesta Pasta');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 8 HOUR), 'Pesto Pasta');

INSERT INTO MEAL_ORDER (TIME_MEAL_ORDERED, MEAL_NAME)
VALUES (DATE_ADD(NOW(), INTERVAL 9 HOUR), 'Spaghetti Bolognese');


SELECT NAME, COUNT(*) AS NUM_OF_ORDERS
FROM MEAL
GROUP BY NAME;

SELECT SUM(PRICE) AS TOTAL_REVENUE
FROM MEAL
WHERE PRICE > 15;

SELECT COUNT(*) AS NUM_OF_MEALS
FROM MEAL
WHERE CALORIES > 500;

SELECT SUM(PRICE) AS TOTAL_PRICE
FROM MEAL
WHERE LOWER(NAME) LIKE '%s%';

SELECT NAME, COUNT(*) AS NUM_OF_ORDERS
FROM MEAL
WHERE DATE_ORDERED < '2023-05-15 01:14:00'
GROUP BY NAME;