SELECT MAX(PRICE) AS MAX_PRICE
FROM MEAL
WHERE CALORIES > 500;

SELECT AVG(CALORIES) AS AVG_CALORIES
FROM MEAL
WHERE PRICE > 15;

SELECT NAME, PRICE
FROM MEAL
HAVING PRICE = MAX(PRICE);

SELECT NAME, PRICE
FROM MEAL
GROUP BY NAME, PRICE
HAVING PRICE < AVG(PRICE);

SELECT NAME, PRICE, CALORIES
FROM MEAL
WHERE PRICE < (SELECT AVG(PRICE) FROM MEAL) AND CALORIES > 600;