ALTER TABLE INGREDIENT
MODIFY NAME VARCHAR(255) NOT NULL UNIQUE,
MODIFY CONTAINS_LACTOSE BOOLEAN NOT NULL,
MODIFY VEGETARIAN BOOLEAN NOT NULL,
MODIFY VEGAN BOOLEAN NOT NULL,
MODIFY GLUTEN_FREE BOOLEAN NOT NULL;